# =============================================================================
# ZeroNAT Terraform Module — User-Data Generation
# =============================================================================
#
# Renders a KEY=VALUE string for the ZeroNAT agent's user-data configuration.
# The agent reads this via IMDSv2 at boot (see agent/imds/userdata.go).
#
# Design principles:
#   - Only non-default values are included to keep user-data minimal.
#   - In single mode, HA settings are omitted entirely (ZERONAT_HA_ENABLED
#     defaults to false in the agent).
#   - Instance A gets ZERONAT_TAKEOVER_ON_BOOT=true so it creates/replaces
#     routes once the agent is fully initialized (zero-downtime deployment).
#   - Instance B does NOT get TAKEOVER_ON_BOOT to avoid a race condition
#     when both nodes start simultaneously during initial cluster deployment.
#
# Config keys reference: agent/config/config.go (lines 50-79)
# =============================================================================

locals {
  # HA settings — only included when mode = "cluster"
  ha_vars = var.mode == "cluster" ? merge(
    # Always enable HA in cluster mode
    { ZERONAT_HA_ENABLED = "true" },

    # Only include non-default values to keep user-data minimal.
    # Default group tag key is "zeronat:group" — agent/discovery/discovery.go:34
    var.group_tag_key != "zeronat:group" ? { ZERONAT_GROUP_TAG_KEY = var.group_tag_key } : {},

    # Default control port is 7946 — agent/discovery/discovery.go:31
    var.control_port != 7946 ? { ZERONAT_CONTROL_PORT = tostring(var.control_port) } : {},

    # Agent default heartbeat interval is 1s
    var.heartbeat_interval != null ? { ZERONAT_HEARTBEAT_INTERVAL = var.heartbeat_interval } : {},

    # Agent default dead threshold is 3
    var.dead_threshold != null ? { ZERONAT_DEAD_THRESHOLD = tostring(var.dead_threshold) } : {},

    # Default peer scan interval is 60s — agent/discovery/discovery.go:37
    var.peer_scan_interval != null ? { ZERONAT_PEER_SCAN_INTERVAL = var.peer_scan_interval } : {},
  ) : {}

  # Shared settings — apply to both single and cluster modes.
  # Only included when they differ from agent defaults.
  shared_vars = merge(
    # Agent default metrics addr is ":9100"
    var.metrics_addr != ":9100" ? { ZERONAT_METRICS_ADDR = var.metrics_addr } : {},

    # Agent default web addr is "127.0.0.1:8080" (localhost only).
    # Set to override, e.g. "0.0.0.0:8080" to allow access from the VPC.
    var.web_addr != null ? { ZERONAT_WEB_ADDR = var.web_addr } : {},
  )

  # Merge HA + shared vars into the base user-data map (shared by both instances)
  userdata_vars = merge(local.ha_vars, local.shared_vars)

  # Instance A user-data: includes ZERONAT_TAKEOVER_ON_BOOT=true so the agent
  # creates/replaces 0.0.0.0/0 routes once fully initialized. This ensures
  # zero-downtime deployments — traffic is only routed to the instance after
  # iptables, conntrackd, and health checks are ready.
  userdata_a_vars = merge(local.userdata_vars, { ZERONAT_TAKEOVER_ON_BOOT = "true" })

  # Instance B user-data: NO TAKEOVER_ON_BOOT. During initial cluster deploy,
  # only instance A should take over routes to avoid a race condition where both
  # nodes try to claim routes simultaneously. Instance B starts as standby and
  # only takes over routes via the normal failover path if A becomes unhealthy.
  userdata_b_vars = local.userdata_vars

  # Render as newline-separated KEY=VALUE strings.
  # The agent's ParseKeyValue function (agent/imds/userdata.go:58-72) skips
  # empty lines and lines starting with "#".
  userdata_a = join("\n", concat(
    ["# ZeroNAT agent configuration — instance A (auto-generated by Terraform)"],
    [for k, v in local.userdata_a_vars : "${k}=${v}"],
  ))

  userdata_b = join("\n", concat(
    ["# ZeroNAT agent configuration — instance B (auto-generated by Terraform)"],
    [for k, v in local.userdata_b_vars : "${k}=${v}"],
  ))
}
