# Kernel parameters for ZeroNAT.
# Installed to /etc/sysctl.d/90-zeronat.conf during AMI bake by packer-provision-aws.sh.

net.ipv4.ip_forward = 1
net.netfilter.nf_conntrack_max = 262144
net.netfilter.nf_conntrack_tcp_timeout_established = 3600
net.netfilter.nf_conntrack_tcp_timeout_time_wait = 30
net.netfilter.nf_conntrack_acct = 1
net.netfilter.nf_conntrack_tcp_be_liberal = 1
net.netfilter.nf_conntrack_tcp_loose = 1
kernel.panic = 10
kernel.panic_on_oops = 1
